[[languages.cpp.environments]]
CXX = "g++"
CXXFLAGS = [
    "-std=gnu++20",
    "-O2",
    "-Wall",
    "-Wextra",
    "-mtune=native",
    "-march=native",
    "-fconstexpr-depth=2147483647",
    "-fconstexpr-loop-limit=2147483647",
    "-fconstexpr-ops-limit=2147483647"
]